apiVersion: v2
name: phpldapadmin
version: 0.1.3
appVersion: 0.7.1
description: Web-based LDAP browser to manage your LDAP server
keywords:
  - phpldapadmin
  - openldap
  - userrights
home: http://phpldapadmin.sourceforge.net
icon: http://phpldapadmin.sourceforge.net/wiki/images/d/d4/Logo.jpg
maintainers:
  - name: iunera
    email: contact@iunera.com
    url: https://www.iunera.com
