{{- if eq .Values.existingEnvSecret.enabled false }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: "{{ $value | b64enc }}"
  {{- end }}
{{- end }}

{{- if .Values.tls.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dex.fullname" . }}-tls
  labels:
    app: {{ template "dex.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
    tls.crt: {{ .Values.tls.certificate | b64enc }}
    tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
