Release "test" has been upgraded. Happy Helming!
NAME: test
LAST DEPLOYED: Thu Jun  8 13:11:30 2023
NAMESPACE: default
STATUS: pending-upgrade
REVISION: 6
HOOKS:
---
# Source: springboot/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "test-springboot-test-connection"
  labels:
    helm.sh/chart: springboot-2.0.0
    app.kubernetes.io/name: springboot
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['test-springboot:8080']
  restartPolicy: Never
MANIFEST:
---
# Source: springboot/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-springboot
  labels:
    helm.sh/chart: springboot-2.0.0
    app.kubernetes.io/name: springboot
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: springboot/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-springboot
  labels:
    helm.sh/chart: springboot-2.0.0
    app.kubernetes.io/name: springboot
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: springboot
    app.kubernetes.io/instance: test
---
# Source: springboot/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-springboot
  labels:
    helm.sh/chart: springboot-2.0.0
    app.kubernetes.io/name: springboot
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: springboot
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: springboot
        app.kubernetes.io/instance: test
    spec:
      serviceAccountName: test-springboot
      securityContext:
        {}
      containers:
        - name: springboot
          securityContext:
            {}
          image: "iunera/springboot-dummy:2.0.0"
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            {}

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=springboot,app.kubernetes.io/instance=test" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
