apiVersion: v1
description: iunera Apache Superset (incubating) is a modern, enterprise-ready business intelligence web application
name: superset
version: 1.1.13
appVersion: "0.38.0"
maintainers:
  - name: iunera
    email: contact@iunera.com
    url: https://www.iunera.com