
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pivot.fullname" . }}-config
  labels:
    app: {{ template "pivot.name" . }}
    chart: {{ template "pivot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
{{ toYaml .Values.config | indent 2 }}
