{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "openldap.fullname" . }}
spec:
  secretName: {{ .Values.tls.secret }}
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: {{ template "openldap.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  # organization:
  # - {{ .Values.env.LDAP_ORGANISATION }}
  dnsNames:
  - {{ template "openldap.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  - {{ template "openldap.fullname" . }}.{{ .Release.Namespace }}
  - {{ template "openldap.fullname" . }}
  - localhost
{{ end }}
