apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wordpress.fullname" . }}-customuploadsini
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  uploads.ini: |+
    {{- .Values.customuploadsini| nindent 4 }}