      # https://github.com/helm/charts-repo-actions-demo/blob/main/.github/workflows/release.yaml

name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  chart:
    name: Release Charts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_SKIP_EXISTING: "false"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # CR_RELEASE_NAME_TEMPLATE: "iunera-helm-charts-{{ .Version }}"
        with:
          charts_dir: charts
